version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 30s
      interval: 10s
      retries: 5
      start_period: 5s

    networks:
      - db-net

  redis:
    image: redis
    container_name: cache

    ports:
      - 6379:6379

    networks:
      - cache-net

  zipkin:
    image: openzipkin/zipkin
    container_name: otel
    ports:
      - 9411:9411
    networks:
      - otel-net

  backend:
    container_name: backend
    build:
      context: backend
    command: http

    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB:-postgres}
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWD:-secret}
      HTTP_SERVER_PORT: 80
      CACHE_URI: redis:6379

      TRACER_ENDPOINT: http://otel:9411/api/v2/spans
      TRACE_ENABLED: true

      # Kong
      KONG_URL: http://kong-gateway:8001
      KONG_CONSUMER: auth-consumer
      KONG_JWT_KEY: auth-jwt

    ports:
      - 5000:80

    depends_on:
      - postgres
      - redis
      - zipkin

    networks:
      - db-net
      - kong-net
      - otel-net
      - cache-net

    healthcheck:
      test: [ "CMD-SHELL", "curl", "http://localhost/health" ]
      timeout: 30s
      interval: 10s
      retries: 5
      start_period: 5s

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      VUE_APP_API_URL: http://backend

    ports:
      - 8080:80

    networks:
      - kong-net

  kong-gateway:
    build:
      dockerfile: .docker/Dockerfile.kong
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
    depends_on:
      - backend
    volumes:
      - .:/kong/declarative
    networks:
      - kong-net

networks:
  db-net:
  kong-net:
  otel-net:
  cache-net:
