version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 30s
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis
    container_name: redis

    ports:
      - 6379:6379

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
