// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/uesleicarvalhoo/sorveteria-tres-estrelas/entity"

	time "time"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *UseCase) GetAll(ctx context.Context) ([]entity.Sale, error) {
	ret := _m.Called(ctx)

	var r0 []entity.Sale
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Sale); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Sale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPeriod provides a mock function with given fields: ctx, start, end
func (_m *UseCase) GetByPeriod(ctx context.Context, start time.Time, end time.Time) ([]entity.Sale, error) {
	ret := _m.Called(ctx, start, end)

	var r0 []entity.Sale
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.Sale); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Sale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterSale provides a mock function with given fields: ctx, desc, payment, cart
func (_m *UseCase) RegisterSale(ctx context.Context, desc string, payment entity.PaymentType, cart entity.Cart) (entity.Sale, error) {
	ret := _m.Called(ctx, desc, payment, cart)

	var r0 entity.Sale
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.PaymentType, entity.Cart) entity.Sale); ok {
		r0 = rf(ctx, desc, payment, cart)
	} else {
		r0 = ret.Get(0).(entity.Sale)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, entity.PaymentType, entity.Cart) error); ok {
		r1 = rf(ctx, desc, payment, cart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
