// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	payments "github.com/uesleicarvalhoo/sorveteria-tres-estrelas/payments"

	time "time"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Reader) GetAll(ctx context.Context) ([]payments.Payment, error) {
	ret := _m.Called(ctx)

	var r0 []payments.Payment
	if rf, ok := ret.Get(0).(func(context.Context) []payments.Payment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payments.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBetween provides a mock function with given fields: ctx, startAt, endAt
func (_m *Reader) GetBetween(ctx context.Context, startAt time.Time, endAt time.Time) ([]payments.Payment, error) {
	ret := _m.Called(ctx, startAt, endAt)

	var r0 []payments.Payment
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []payments.Payment); ok {
		r0 = rf(ctx, startAt, endAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payments.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startAt, endAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReader(t mockConstructorTestingTNewReader) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
