// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	transaction "github.com/uesleicarvalhoo/sorveteria-tres-estrelas/backend/transaction"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Reader) GetAll(ctx context.Context) ([]transaction.Transaction, error) {
	ret := _m.Called(ctx)

	var r0 []transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]transaction.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []transaction.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBetween provides a mock function with given fields: ctx, startAt, endAt
func (_m *Reader) GetBetween(ctx context.Context, startAt time.Time, endAt time.Time) ([]transaction.Transaction, error) {
	ret := _m.Called(ctx, startAt, endAt)

	var r0 []transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]transaction.Transaction, error)); ok {
		return rf(ctx, startAt, endAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []transaction.Transaction); ok {
		r0 = rf(ctx, startAt, endAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startAt, endAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
