// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	transaction "github.com/uesleicarvalhoo/sorveteria-tres-estrelas/backend/transaction"

	uuid "github.com/google/uuid"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// DeleteTransaction provides a mock function with given fields: ctx, id
func (_m *UseCase) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByPeriod provides a mock function with given fields: ctx, startAt, endAt
func (_m *UseCase) GetByPeriod(ctx context.Context, startAt time.Time, endAt time.Time) ([]transaction.Transaction, error) {
	ret := _m.Called(ctx, startAt, endAt)

	var r0 []transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]transaction.Transaction, error)); ok {
		return rf(ctx, startAt, endAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []transaction.Transaction); ok {
		r0 = rf(ctx, startAt, endAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startAt, endAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: ctx
func (_m *UseCase) GetTransactions(ctx context.Context) ([]transaction.Transaction, error) {
	ret := _m.Called(ctx)

	var r0 []transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]transaction.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []transaction.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterTransaction provides a mock function with given fields: ctx, value, operation, desc
func (_m *UseCase) RegisterTransaction(ctx context.Context, value float32, operation transaction.Type, desc string) (transaction.Transaction, error) {
	ret := _m.Called(ctx, value, operation, desc)

	var r0 transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float32, transaction.Type, string) (transaction.Transaction, error)); ok {
		return rf(ctx, value, operation, desc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float32, transaction.Type, string) transaction.Transaction); ok {
		r0 = rf(ctx, value, operation, desc)
	} else {
		r0 = ret.Get(0).(transaction.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, float32, transaction.Type, string) error); ok {
		r1 = rf(ctx, value, operation, desc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
