name: run golangci-lint

on:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

        with:
          version: "v1.51.2"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-pkg-cache: false
          skip-build-cache: false
          skip-go-installation: false
          only-new-issues: false
