name: run golangci-lint

on:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses:  golangci/golangci-lint-action@v3.4.0
        with:
          working-directory: backend
          skip-pkg-cache: false
          skip-build-cache: false
          only-new-issues: false
