name: build backedn docker image, publish to github packages and deploy in remote server

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  RELEASE_TAG: ${{ github.ref_name }}
  BACKEND_IMAGE_NAME: ${{ github.repository }}
  BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  FRONTEND_CONTAINER_NAME: ${{ secrets.FRONTEND_CONTAINER_NAME }}

jobs:
  backend-build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ BACKENDTEND_IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  backend-deploy:
    runs-on: ubuntu-latest
    needs: backend-build-and-push-image
    steps:
      - name: Run docker container in remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ BACKENDTEND_IMAGE_NAME }}:${{ env.RELEASE_TAG }}
            docker stop ${{ env.BACKEND_CONTAINER_NAME }} || true
            docker rm ${{ env.BACKEND_CONTAINER_NAME }} || true
            docker run -d --restart=always \
            --health-cmd="curl --fail localhost:${{ secrets.HTTP_SERVER_PORT }}/health" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            --name ${{ env.BACKEND_CONTAINER_NAME }} \
            -p ${{ secrets.HTTP_SERVER_PORT }}:${{ secrets.HTTP_SERVER_PORT }} \
            -e DATABASE_USER=${{ secrets.DATABASE_USER }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -e CACHE_URI=${{ secrets.CACHE_URI }} \
            -e CACHE_PASSWORD=${{ secrets.CACHE_PASSWORD }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e LOG_LEVEL=${{ secrets.LOG_LEVEL }} \
            -e SERVICE_NAME=${{ secrets.BACKEND_SERVICE_NAME }} \
            -e SERVICE_VERSION=${{ env.RELEASE_TAG }} \
            -e HTTP_SERVER_PORT=${{ secrets.HTTP_SERVER_PORT }} \
            -e TRACER_ENDPOINT=${{ secrets.TRACER_ENDPOINT }} \
            -e TRACER_ENABLED=${{ secrets.TRACER_ENABLED }} \
            -e KONG_URL=${{ secrets.KONG_URL }} \
            -e KONG_CONSUMER={{ secrets.KONG_CONSUMER }} \
            -e KONG_JWT_KEY={{ secrets.KONG_JWT_KEY }} \
            --network=${{ secrets.DOCKER_NETWORK }} \
             ${{ env.REGISTRY }}/${{ BACKENDTEND_IMAGE_NAME }}:${{ env.RELEASE_TAG }}

  frontend-build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: frontend-build-and-push-image
    steps:
      - name: Run docker container in remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.RELEASE_TAG }}
            docker stop ${{ env.FRONTEND_CONTAINER_NAME }} || true
            docker rm ${{ env.FRONTEND_CONTAINER_NAME }} || true
            docker run -d \
            --name ${{ env.FRONTEND_CONTAINER_NAME }} \
            -p ${{ secrets.HTTP_SERVER_PORT }}:80 \
            -e VUE_APP_API_URL=${{ secrets.BACKEND_URL }} \
            --network=${{ secrets.DOCKER_NETWORK }} \
             ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.RELEASE_TAG }}
