name: run tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: Test build
        run: go build -v ./...

      - name: Run unit tests
        run: go test ./... -tags=unit -race -v

      - name: Run integration tests
        run: go test ./... -tags=integration -race -v
