name: run tests

on:
  pull_request:
    branches:
      - "main"

env:
  GO_VERSION: "1.20.x"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test build
        working-directory: backend
        run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run unit tests
        working-directory: backend
        run: go test ./... -tags=unit -race -v

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run integration tests
        working-directory: backend
        run: go test ./... -tags=integration -race -v
